### ISSUE TITLE
[Bug] log_modify_path() returns failure but still redirects log output

### ISSUE THREAD

**Issue by jgabaut** [khushal-banks/log_bank#30] opened 2024-04-03 02:58 UTC
Currently, calling

```c
int res = log_modify_path("./log.txt");
```

Results in nonzero being returned, but the log is still redirected. This can't be expected behaviour.

**Comment by khushal-banks** [comment] 2024-04-03 04:15
This returns in non-zero because there is no custom file support. I have opened a new issue #31 for custom file names.

logs are still redirected is an issue. Solution of this issue will be merged with the solution of #31 
I will keep this open to test after i have custom file support.

This will be test code:
```
int
main() {

    /* Printing Version */
    LOG(LOG_INFO, "Version: %s", LOG_VERSION);

    // log_modify_path(NULL);         // to use auto-generated file (currently supported)
    log_modify_path("log.txt");       // this should return error and shouldn't redirect logs in current release

    /* Writing samples with LOG_MACRO/TRACE_MACRO to auto-generated file */
    test_log();
    test_trace();

    return 0;
}

```

# Expected behavior in next release

logs.txt file will be generated in LOG_FILE_DIR directory configured at compile time.
By default this file will be in logs/log.txt

If someone supplies a full path like `log_modify_path("logs/log.txt")` this should also go to the same file.

# Note
Use of "./ or ../" might not be supported. I will see what i can do .. no promises

# Summary
Because log directory will always be fixed. It will optional to add the log directory or else this function will automatically add directory name to convert to full path.

**Comment by khushal-banks** [comment] 2024-04-03 07:50
Removed the TRACE macro
and added the configuration of enabling or disabling LOG macro through [Generic-Make](https://github.com/khushal-banks/log_bank/blob/main/examples/Generic-Make) of the main application

Refer, new section of [COMPILATION.md](https://github.com/khushal-banks/log_bank/blob/main/docs/COMPILATION.md#compilation-flags-for-main-application) for details

**Comment by khushal-banks** [comment] 2024-04-03 07:57
This issue is not yet fixed

**Comment by khushal-banks** [comment] 2024-04-03 08:09
> Currently, calling
> 
> ```c
> int res = log_modify_path("./log.txt");
> ```
> 
> Results in nonzero being returned, but the log is still redirected. This can't be expected behaviour.

OP requires to support "log.txt"
for this LOG_FILE_EXTN compilation flag should be changed to .txt (instead of default value .log)
```
DEFS_DEBUG                += -DLOG_LEVEL=1 -DLOG_FILE_DIR=\"logs/\" -DLOG_FILE_EXTN=\".txt\"
DEFS_RELEASE              += -DLOG_LEVEL=3 -DLOG_FILE_DIR=\"logs/\" -DLOG_FILE_EXTN=\".txt\"
```

or else, it would be considered as incorrect name and logging would continue on previous stream (i.e., stderr)

> OP also requires to support "./" as relative path which is not supported.
> one can either pass "log.txt" or "logs/log.txt"

Assuming relative paths will not be a necessary requirement and closing this.
Relative paths are hard to support so would label it as a limitation as well

**Closed by khushal-banks** 2024-04-03 08:09 UTC
Labels: bug, ! Critical, ! Limitation :-1:
